[platformio]
default_envs = waveshare-amoled-175c
test_dir = tests

[env:waveshare-amoled-175c]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 32MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -I.
    -Iconfig
    -Isrc
    -DBOARD_HAS_PSRAM=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DWAVESHARE_AMOLED_175C=1
    -DHAS_SCREEN=1
    -DUSE_ARDUINO_GFX=1
    -DTFT_DATABUS_N=1
    -DTFT_DISPLAY_DRIVER_N=41
    -DTFT_ROTATION=0
    -DTFT_USE_CANVAS=1
    -DROTATION=3
lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.6.7
    https://github.com/lewisxhe/SensorsLib.git

[env:native]
platform = native
test_framework = googletest
build_flags =
    -I.
    -Isrc
    -Iconfig
    -std=c++17
test_build_src = yes
build_src_filter = +<*> -<main.cpp>
